// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQfNGjUXrHJkaMYdrKH10S9xcMG8Pk1g',
    appId: '1:795919157602:web:d82d06c72c40141066c43b',
    messagingSenderId: '795919157602',
    projectId: 'chattapp-4e696',
    authDomain: 'chattapp-4e696.firebaseapp.com',
    storageBucket: 'chattapp-4e696.firebasestorage.app',
    measurementId: 'G-FMY55S3TK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaFyBlCj_HRenefBKW4C73SJXQ9NL9Ilg',
    appId: '1:795919157602:android:7fd8f0800b89f4ba66c43b',
    messagingSenderId: '795919157602',
    projectId: 'chattapp-4e696',
    storageBucket: 'chattapp-4e696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GPBgL28wR2NDSqX5P8DO7_1XVl4bXNQ',
    appId: '1:795919157602:ios:8c34d11653d45c0566c43b',
    messagingSenderId: '795919157602',
    projectId: 'chattapp-4e696',
    storageBucket: 'chattapp-4e696.firebasestorage.app',
    iosBundleId: 'com.example.chatTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GPBgL28wR2NDSqX5P8DO7_1XVl4bXNQ',
    appId: '1:795919157602:ios:8c34d11653d45c0566c43b',
    messagingSenderId: '795919157602',
    projectId: 'chattapp-4e696',
    storageBucket: 'chattapp-4e696.firebasestorage.app',
    iosBundleId: 'com.example.chatTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClQfNGjUXrHJkaMYdrKH10S9xcMG8Pk1g',
    appId: '1:795919157602:web:4a8ad9038322220366c43b',
    messagingSenderId: '795919157602',
    projectId: 'chattapp-4e696',
    authDomain: 'chattapp-4e696.firebaseapp.com',
    storageBucket: 'chattapp-4e696.firebasestorage.app',
    measurementId: 'G-66D9PGT8KT',
  );
}
